version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on $(date)
      - echo Building Next.js application
      - npm run build

artifacts:
  files:
    - '**/*'

